//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Macdonalds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DishAndElement
    {
        public int Id { get; set; }
        public Nullable<int> DishId { get; set; }
        public Nullable<int> ElementId { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Element Element { get; set; }
    }
}
